bug/urls.py
from django.urls import path

from .views import BugListView, BugDetailView, BugCreateView, IndexView


app_name = "bug"
urlpatterns = [
    path("", IndexView.as_view(), name="index"), 
    path("bug_list/", BugListView.as_view(), name="bug_list"),
    path("<int:pk>/", BugDetailView.as_view(), name="bug_detail"),
    path("register/", BugCreateView.as_view(), name="register_bug")
]

bugsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("bug/", include("bug.urls")),
    path('admin/', admin.site.urls),
]

bug/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.core.exceptions import ValidationError

# Create your models here.
class Bug(models.Model):
    BUG_TYPES = [
        ("error", "error"),
        ("new_feature", "new feature"),
        ("improvement", "improvement"),
        ("test_case", "test case")
    ]
    BUG_STATUSES = [
        ("to_do", "to do"),
        ("assigned", "assigned"),
        ("in_progress", "in progress"),
        ("under_review", "under review"),
        ("done", "done")
    ]
    description = models.TextField(max_length=500)
    bug_type = models.CharField(max_length=20, choices=BUG_TYPES)
    report_date = models.DateField(default=timezone.now)
    status = models.CharField(max_length=20, choices=BUG_STATUSES)

    def __str__(self):
        return self.description

    def clean(self):
        # Check if bug_type and status are valid choices
        if self.bug_type not in dict(self.BUG_TYPES):
            raise ValidationError("Invalid bug_type choice")
        if self.status not in dict(self.BUG_STATUSES):
            raise ValidationError("Invalid status choice")

bug/views.py
from django.views import generic

from django.urls import reverse_lazy

from .models import Bug

# Create your views here.
class IndexView(generic.TemplateView):
    template_name = "bug/index.html"

class BugCreateView(generic.CreateView):
    model = Bug
    template_name = "bug/add_bug.html"
    fields = ["description", "bug_type", "report_date", "status"]
    success_url = reverse_lazy("bug:bug_list")

class BugDetailView(generic.DetailView):
    model = Bug
    context_object_name = "bug_detail"
    template_name = "bug/bug_detail.html"

class BugListView(generic.ListView):
    model = Bug
    context_object_name = "bug_list"
    template_name = "bug/bug_list.html"

bug/templates/bug/add_bug.html
<h1>Add New Bug</h1>
<form action="" method="post">
    {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Save">
</form>

bug/templates/bug/bug_detail.html
<h1>View A Bug</h1>

<ul>                       
    <li>Status: {{bug_detail.status}}</li>
    <li>Description: {{bug_detail.description}}</li>
    <li>Type:{{ bug_detail.bug_type }} </li>
    <li>Reported Date: {{bug_detail.report_date}}</li>
        
</ul>

bug/templates/bug/bug_list.html
<h1>Bug List</h1>
<ul>
    {% for bug in bug_list%}
  
    <li><a href="{% url 'bug:bug_detail' bug.id %}">{{ bug.description }}</a></li>
    
    {% endfor %}
</ul>


   

bug/templates/bug/index.html
<h1>Welcome to the Bug Tracker</h1>